name: Build and Deploy to Docker Hub and GCP Cloud Run

on:
  push:
    branches:
      - main

env:
  IMAGE_BASE_NAME: evdev3/neural-nexus-sample-messaging-api
  IMAGE_TAG: ${{ github.sha }}
  SERVICE_NAME: neural-nexus-sample-messaging-api
  REGION: us-east1
  PROJECT_ID: neuralnexus-467517

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push updated app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            docker.io/${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64
          cache-from: type=registry,ref=docker.io/${{ env.IMAGE_BASE_NAME }}:latest
          cache-to: type=inline

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          FULL_IMAGE_NAME="docker.io/${IMAGE_BASE_NAME}:${IMAGE_TAG}"
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=$FULL_IMAGE_NAME \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --memory=2Gi \
            --cpu=1 \
            --concurrency=80 \
            --set-env-vars='HUGGINGFACE_TOKEN=${{secrets.HUGGINGFACE_TOKEN}}'